# plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files and directories from Jekyll build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - run_docker.sh
  - start_in_docker.sh
  - image_editing/
  - "*.sh"
  - node_modules/
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .git/
  - .gitignore
  - "*.tmp"
  - "*.bak"

# Metadata
title: "Army Depot Berlin"
description: "Bekleidung Ausrüstung Outdoor Camping Trekking Militaria im besten sortierten Army Shop in Berlin Charlottenburg!"
tagline: "Bekleidung Ausrüstung Outdoor Camping Trekking Militaria im besten sortierten Army Shop in Berlin Charlottenburg!"
title_prefix: "Army Depot Berlin - "
title_postfix: ""
logo: "/assets/images/logo.svg"
locale: "de_DE"
author:
  name: "Army Depot Berlin"
  email: "kontakt@armydepotberlin.de"
image:
  path: /assets/images/logo.svg
  height: 100
  width: 100
  alt: Army Depot Logo

# GitHub Pages - custom domain
domain: "armydepotberlin.de"
url: "https://armydepotberlin.de"
baseurl: ""

sass:
  sass_dir: _sass
  style: compressed

# ======== Army Depot settings ========

# Default background image
default_background_image: "/assets/images/vorne_flaggen.webp"
sidebar_image: "/assets/images/camo_woodland.svg"

# Permalink structure for posts
permalink: pretty
