# sass:
#   sass_dir: _sass
#   style: compressed # or expanded

# TODO
title_prefix: "Army Depot Berlin - "
title_postfix: " - Bekleidung Ausrüstung Outdoor Camping Trekking Militär"

# Default background image
default_background_image: "/assets/images/background.webp"