# plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Metadata
title: "Army Depot Berlin"
description: "Army Depot Berlin - Bekleidung Ausrüstung Outdoor Camping Trekking Militär"
tagline: "Army Depot Berlin - Bekleidung Ausrüstung Outdoor Camping Trekking Militär"
title_prefix: "Army Depot Berlin - "
title_postfix: " - Bekleidung Ausrüstung Outdoor Camping Trekking Militär"
logo: "/assets/images/logo.svg"
locale: "de_DE"
author:
  name: "Army Depot Berlin"
  email: "army.depot.berlin@gmail.com"
image:
  path: /assets/images/logo.svg
  height: 100
  width: 100
  alt: Army Depot Logo

# GitHub Pages
domain: "devintdha.github.io"
url: "https://devintdha.github.io"
baseurl: "/army-depot-berlin"

sass:
  sass_dir: _sass
  style: compressed

# Default background image
default_background_image: "/assets/images/background.webp"
sidebar_image: "/assets/images/camo_woodland.svg"


# Permalink structure for posts
permalink: /neuigkeiten/:year-:month-:day-:title/

# Make last slash optional
permalink_style: pretty

